"""Every language of the profile README, and the regions shown on LANGUAGES.md.

code: the file name (i18n/README.<code>.md); "en" is README.md and "ja" is README.ja.md.
"""

# code: (native name, English name, Japanese name, right-to-left)
LANGS = {
    "en": ("English (US)", "English (US)", "英語（米国式）", False),
    "ja": ("日本語", "Japanese", "日本語", False),
    "ko": ("한국어", "Korean", "韓国語", False),
    "zh-Hans": ("简体中文", "Chinese (Simplified)", "中国語（簡体字）", False),
    "zh-Hant": ("繁體中文", "Chinese (Traditional)", "中国語（繁体字・香港台湾式）", False),
    "mn": ("Монгол", "Mongolian", "モンゴル語", False),
    "tl": ("Tagalog", "Tagalog", "タガログ語", False),
    "vi": ("Tiếng Việt", "Vietnamese", "ベトナム語", False),
    "lo": ("ລາວ", "Lao", "ラオス語", False),
    "km": ("ខ្មែរ", "Khmer", "クメール語", False),
    "th": ("ไทย", "Thai", "タイ語", False),
    "my": ("မြန်မာ", "Burmese", "ビルマ語", False),
    "ms": ("Bahasa Melayu", "Malay", "マレー語", False),
    "id": ("Bahasa Indonesia", "Indonesian", "インドネシア語", False),
    "uz": ("Oʻzbekcha", "Uzbek", "ウズベク語", False),
    "kk": ("Қазақша", "Kazakh", "カザフ語", False),
    "ky": ("Кыргызча", "Kyrgyz", "キルギス語", False),
    "tg": ("Тоҷикӣ", "Tajik", "タジク語", False),
    "tk": ("Türkmençe", "Turkmen", "トルクメン語", False),
    "hi": ("हिन्दी", "Hindi", "ヒンディー語", False),
    "bn": ("বাংলা", "Bengali", "ベンガル語", False),
    "si": ("සිංහල", "Sinhala", "シンハラ語", False),
    "ta": ("தமிழ்", "Tamil", "タミル語", False),
    "ne": ("नेपाली", "Nepali", "ネパール語", False),
    "ur": ("اردو", "Urdu", "ウルドゥ語", True),
    "dz": ("རྫོང་ཁ", "Dzongkha", "ゾンカ語", False),
    "dv": ("ދިވެހި", "Dhivehi", "ディベヒ語", True),
    "prs": ("دری", "Dari", "ダリー語", True),
    "ps": ("پښتو", "Pashto", "パシュトゥ語", True),
    "ar": ("العربية", "Arabic", "アラビア語", True),
    "tr": ("Türkçe", "Turkish", "トルコ語", False),
    "ka": ("ქართული", "Georgian", "グルジア語", False),
    "fa": ("فارسی", "Persian", "ペルシャ語", True),
    "ku": ("Kurdî (Kurmancî)", "Kurdish (Kurmanji)", "クルド語", False),
    "he": ("עברית", "Hebrew", "ヘブライ語", True),
    "az": ("Azərbaycanca", "Azerbaijani", "アゼルバイジャン語", False),
    "ru": ("Русский", "Russian", "ロシア語", False),
    "be": ("Беларуская", "Belarusian", "ベラルーシ語", False),
    "uk": ("Українська", "Ukrainian", "ウクライナ語", False),
    "cs": ("Čeština", "Czech", "チェコ語", False),
    "sk": ("Slovenčina", "Slovak", "スロバキア語", False),
    "hu": ("Magyar", "Hungarian", "ハンガリー語", False),
    "hr": ("Hrvatski", "Croatian", "クロアチア語", False),
    "ro": ("Română", "Romanian", "ルーマニア語", False),
    "hy": ("Հայերեն", "Armenian", "アルメニア語", False),
    "kl": ("Kalaallisut", "Greenlandic", "グリーンランド語", False),
    "is": ("Íslenska", "Icelandic", "アイスランド語", False),
    "nb": ("Norsk", "Norwegian", "ノルウェー語", False),
    "sv": ("Svenska", "Swedish", "スウェーデン語", False),
    "fi": ("Suomi", "Finnish", "フィンランド語", False),
    "lt": ("Lietuvių", "Lithuanian", "リトアニア語", False),
    "lv": ("Latviešu", "Latvian", "ラトビア語", False),
    "et": ("Eesti", "Estonian", "エストニア語", False),
    "da": ("Dansk", "Danish", "デンマーク語", False),
    "en-GB": ("English (UK)", "English (UK)", "英語（英国式）", False),
    "de": ("Deutsch", "German", "ドイツ語", False),
    "fr": ("Français", "French", "フランス語", False),
    "nl": ("Nederlands", "Dutch", "オランダ語", False),
    "rm": ("Rumantsch", "Romansh", "ロマンシュ語", False),
    "es": ("Español", "Spanish", "スペイン語", False),
    "pt": ("Português", "Portuguese", "ポルトガル語", False),
    "ca": ("Català", "Catalan", "カタルーニャ語", False),
    "it": ("Italiano", "Italian", "イタリア語", False),
    "la": ("Latina", "Latin", "ラテン語", False),
    "mt": ("Malti", "Maltese", "マルタ語", False),
    "sl": ("Slovenščina", "Slovenian", "スロベニア語", False),
    "bs": ("Bosanski", "Bosnian", "ボスニア語", False),
    "sr": ("Српски", "Serbian", "セルビア語", False),
    "sq": ("Shqip", "Albanian", "アルバニア語", False),
    "el": ("Ελληνικά", "Greek", "ギリシャ語", False),
    "bg": ("Български", "Bulgarian", "ブルガリア語", False),
    "cnr": ("Crnogorski", "Montenegrin", "モンテネグロ語", False),
    "mk": ("Македонски", "Macedonian", "マケドニア語", False),
    "fr-CA": ("Français (Canada)", "French (Canada)", "フランス語（カナダ）", False),
    "es-419": ("Español (Latinoamérica)", "Spanish (Latin America)", "スペイン語（南米）", False),
    "pt-BR": ("Português (Brasil)", "Portuguese (Brazil)", "ポルトガル語（ブラジル）", False),
    "gn": ("Avañeʼẽ", "Guarani", "グアラニー語", False),
    "ht": ("Kreyòl ayisyen", "Haitian Creole", "クレオール語（ハイチ）", False),
    "mi": ("Te Reo Māori", "Māori", "マオリ語", False),
    "ch": ("Chamoru", "Chamorro", "チャモロ語", False),
    "pau": ("Tekoi er a Belau", "Palauan", "パラオ語", False),
    "gil": ("Taetae ni Kiribati", "Gilbertese", "キリバス語", False),
    "sm": ("Gagana Sāmoa", "Samoan", "サモア語", False),
    "tvl": ("Te Gana Tuvalu", "Tuvaluan", "ツバル語", False),
    "to": ("Lea faka-Tonga", "Tongan", "トンガ語", False),
    "na": ("Dorerin Naoero", "Nauruan", "ナウル語", False),
    "niu": ("Vagahau Niuē", "Niuean", "ニウエ語", False),
    "bi": ("Bislama", "Bislama", "ビスラマ語", False),
    "fj": ("Na Vosa Vakaviti", "Fijian", "フィジー語", False),
    "hif": ("Fiji Baat", "Fiji Hindi", "ヒンドゥスターニー語（フィジー）", False),
    "ty": ("Reo Tahiti", "Tahitian", "タヒチ語", False),
    "mh": ("Kajin M̧ajeļ", "Marshallese", "マーシャル語", False),
    "kab": ("Taqbaylit", "Berber (Kabyle)", "ベルベル語（カビル語）", False),
    "kea": ("Kriolu kabuverdianu", "Cape Verdean Creole", "カーボベルデ語", False),
    "sg": ("Sängö", "Sango", "サンゴ語", False),
    "ti": ("ትግርኛ", "Tigrinya", "ティグリニャ語", False),
    "am": ("አማርኛ", "Amharic", "アムハラ語", False),
    "sw": ("Kiswahili", "Swahili", "スワヒリ語", False),
    "so": ("Soomaali", "Somali", "ソマリ語", False),
    "mg": ("Malagasy", "Malagasy", "マダガスカル語", False),
    "zdj": ("Shikomori", "Comorian", "コモロ語", False),
    "crs": ("Kreol seselwa", "Seychellois Creole", "クレオール語（セーシェル）", False),
    "rn": ("Ikirundi", "Kirundi", "ルンディ語", False),
    "rw": ("Ikinyarwanda", "Kinyarwanda", "ルワンダ語", False),
    "tn": ("Setswana", "Tswana", "ツワナ語", False),
    "af": ("Afrikaans", "Afrikaans", "アフリカーンス語", False),
    "st": ("Sesotho", "Sotho", "ソト語", False),
    "ss": ("SiSwati", "Swati", "スワジ語", False),
}

# (continent id, English, Japanese, [(region English, region Japanese, [codes])])
REGIONS = [
    ("asia", "Asia", "アジア州", [
        ("East Asia", "東アジア", ["ja", "ko", "zh-Hans", "zh-Hant", "mn"]),
        ("Southeast Asia", "東南アジア", ["tl", "vi", "lo", "km", "th", "my", "ms", "id"]),
        ("Central Asia", "中央アジア", ["uz", "kk", "ky", "tg", "tk"]),
        ("South Asia", "南アジア", ["hi", "bn", "si", "ta", "ne", "ur", "dz", "dv", "prs", "ps"]),
        ("West Asia", "西アジア", ["ar", "tr", "ka", "fa", "ku", "he", "az"]),
    ]),
    ("europe", "Europe", "ヨーロッパ州", [
        ("Eastern Europe", "東ヨーロッパ", ["ru", "be", "uk", "cs", "sk", "hu", "hr", "ro", "hy"]),
        ("Northern Europe", "北ヨーロッパ", ["kl", "is", "nb", "sv", "fi", "lt", "lv", "et", "da"]),
        ("Western Europe", "西ヨーロッパ", ["en-GB", "de", "fr", "nl", "rm"]),
        ("Southern Europe", "南ヨーロッパ", ["es", "pt", "ca", "it", "la", "mt", "sl", "hr", "bs", "sr", "sq", "el", "bg", "cnr", "mk"]),
    ]),
    ("americas", "Americas", "アメリカ州", [
        ("North America", "北アメリカ", ["en", "fr-CA"]),
        ("Central America", "中央アメリカ", ["en", "es"]),
        ("Caribbean", "カリブ海地域", ["en", "es", "fr", "pt", "ht"]),
        ("South America", "南アメリカ", ["en", "es-419", "pt-BR", "gn"]),
    ]),
    ("oceania", "Oceania", "オセアニア州", [
        ("Australia and New Zealand", "オーストラリア・ニュージーランド", ["en-GB", "mi"]),
        ("Melanesia, Polynesia and Micronesia", "メラネシア・ポリネシア・ミクロネシア", ["en-GB", "fr", "ch", "pau", "gil", "sm", "tvl", "to", "na", "niu", "bi", "fj", "hif", "ty", "mh"]),
    ]),
    ("africa", "Africa", "アフリカ州", [
        ("North Africa", "北アフリカ", ["kab", "ar"]),
        ("West Africa", "西アフリカ", ["ar", "fr", "en-GB", "kea"]),
        ("Central Africa", "中央アフリカ", ["ar", "fr", "en-GB", "sg", "es", "pt"]),
        ("East Africa", "東アフリカ", ["ar", "ti", "am", "sw", "en-GB", "so", "pt", "mg", "zdj", "fr", "crs", "rn", "rw"]),
        ("Southern Africa", "南アフリカ", ["en-GB", "tn", "af", "st", "ss"]),
    ]),
]

assert all(c in LANGS for _, _, _, regions in REGIONS for _, _, codes in regions for c in codes)
assert all(any(c in codes for _, _, _, regions in REGIONS for _, _, codes in regions) for c in LANGS)
